apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: python-app  # Make sure this matches the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80        # Port on which the service is exposed
      targetPort: 8080 # Port on which the frontend container is listening
  type: LoadBalancer  # Or NodePort if you prefer
